# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build API
      working-directory: VSCR.Api/
      run: dotnet build --configuration Release

    - name: Publish API
      working-directory: VSCR.Api/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy API to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'VisualStudioChatRoulette'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f97e9377566c4cdea31ce492e6c23535 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
